apiVersion: v1
kind: Service

metadata:
  name: newsify-service
  namespace: newsify-ns-3

spec:
  type: NodePort
  selector:
    app: newsify

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30009
